# Generated by Django 3.0.4 on 2020-03-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0002_auto_20200308_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jwtoken',
            name='pub_key',
        ),
        migrations.AddField(
            model_name='jwtoken',
            name='pub_key_id',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='jwtoken',
            name='pub_key_type',
            field=models.TextField(default=''),
        ),
    ]
