# Generated by Django 3.0.4 on 2020-03-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0003_auto_20200308_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jwtoken',
            name='pub_key_id',
        ),
        migrations.RemoveField(
            model_name='jwtoken',
            name='pub_key_type',
        ),
        migrations.AddField(
            model_name='jwtoken',
            name='pub_key',
            field=models.TextField(default=''),
        ),
    ]
