# Generated by Django 3.0.4 on 2020-03-10 22:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkmodel',
            name='counter',
        ),
        migrations.CreateModel(
            name='LinkVisitInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='link.LinkModel')),
            ],
        ),
    ]
